# Generated by Django 5.2 on 2025-05-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount_prince',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
