# Generated by Django 5.2 on 2025-05-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='user_id',
            new_name='user',
        ),
    ]
