# Generated by Django 5.2 on 2025-05-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categories_created_at_categories_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
