# Generated by Django 5.2 on 2025-05-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custom_user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='custom_user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='username',
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
