# Generated by Django 5.2 on 2025-05-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_data', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_address',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customer_orders',
            old_name='customer_address_id',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='customer_orders',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='customer_orders',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customer_payments',
            old_name='user_id',
            new_name='user',
        ),
    ]
